// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpaEllVTqVytYEb0zohfN5JzUG8rTccuc',
    appId: '1:575763057030:web:0f65ff15a44ba3e21fc407',
    messagingSenderId: '575763057030',
    projectId: 'charity-app-14ef4',
    authDomain: 'charity-app-14ef4.firebaseapp.com',
    storageBucket: 'charity-app-14ef4.appspot.com',
    measurementId: 'G-NVTPCGFRLV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJNG36Toah_NMt0z0pR4VjtSFbVjj2eY8',
    appId: '1:575763057030:ios:50456432f59fc9d91fc407',
    messagingSenderId: '575763057030',
    projectId: 'charity-app-14ef4',
    storageBucket: 'charity-app-14ef4.appspot.com',
    iosBundleId: 'com.example.donationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJNG36Toah_NMt0z0pR4VjtSFbVjj2eY8',
    appId: '1:575763057030:ios:03cab2e71fe8dbab1fc407',
    messagingSenderId: '575763057030',
    projectId: 'charity-app-14ef4',
    storageBucket: 'charity-app-14ef4.appspot.com',
    iosBundleId: 'com.example.donationApp.RunnerTests',
  );
}
